# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphics_app.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.buttonZoomIn = QtWidgets.QToolButton(self.centralwidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/icons8-zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonZoomIn.setIcon(icon)
        self.buttonZoomIn.setIconSize(QtCore.QSize(30, 30))
        self.buttonZoomIn.setObjectName("buttonZoomIn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.buttonZoomIn)
        self.buttonZoomOut = QtWidgets.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Assets/icons8-zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonZoomOut.setIcon(icon1)
        self.buttonZoomOut.setIconSize(QtCore.QSize(30, 30))
        self.buttonZoomOut.setObjectName("buttonZoomOut")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.buttonZoomOut)
        self.buttonRotateCCW = QtWidgets.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Assets/icons8-rotate-left-filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRotateCCW.setIcon(icon2)
        self.buttonRotateCCW.setIconSize(QtCore.QSize(30, 30))
        self.buttonRotateCCW.setObjectName("buttonRotateCCW")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.buttonRotateCCW)
        self.buttonRotateCW = QtWidgets.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Assets/icons8-rotate-right-filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRotateCW.setIcon(icon3)
        self.buttonRotateCW.setIconSize(QtCore.QSize(30, 30))
        self.buttonRotateCW.setObjectName("buttonRotateCW")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.buttonRotateCW)
        self.buttonFlipV = QtWidgets.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Assets/icons8-flip-vertical-filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonFlipV.setIcon(icon4)
        self.buttonFlipV.setIconSize(QtCore.QSize(30, 30))
        self.buttonFlipV.setObjectName("buttonFlipV")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.buttonFlipV)
        self.ButtonFlipH = QtWidgets.QToolButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Assets/icons8-flip-horizontal-filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonFlipH.setIcon(icon5)
        self.ButtonFlipH.setIconSize(QtCore.QSize(30, 30))
        self.ButtonFlipH.setObjectName("ButtonFlipH")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ButtonFlipH)
        self.gridLayout.addLayout(self.formLayout, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuView_2 = QtWidgets.QMenu(self.menubar)
        self.menuView_2.setObjectName("menuView_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRotate = QtWidgets.QAction(MainWindow)
        self.actionRotate.setObjectName("actionRotate")
        self.actionFlipV = QtWidgets.QAction(MainWindow)
        self.actionFlipV.setObjectName("actionFlipV")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.menuFile.addAction(self.actionOpen)
        self.menuView.addAction(self.actionRotate)
        self.menuView.addAction(self.actionFlipV)
        self.menuView.addAction(self.actionZoom_Out)
        self.menuView_2.addAction(self.actionZoomIn)
        self.menuView_2.addAction(self.actionZoomOut)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView_2.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonZoomIn.setText(_translate("MainWindow", "+"))
        self.buttonZoomOut.setText(_translate("MainWindow", "-"))
        self.buttonRotateCCW.setText(_translate("MainWindow", "CCW"))
        self.buttonRotateCW.setText(_translate("MainWindow", "CW"))
        self.buttonFlipV.setText(_translate("MainWindow", "FV"))
        self.ButtonFlipH.setText(_translate("MainWindow", "FH"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "Transform"))
        self.menuView_2.setTitle(_translate("MainWindow", "View"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionRotate.setText(_translate("MainWindow", "Rotate (Ctrl + < , Ctrl + >)"))
        self.actionFlipV.setText(_translate("MainWindow", "Flip Vertical (Ctrl + V)"))
        self.actionZoom_Out.setText(_translate("MainWindow", "Flip Horizontal (Ctrl + H)"))
        self.actionZoomIn.setText(_translate("MainWindow", "Zoom In (Ctrl + +)"))
        self.actionZoomOut.setText(_translate("MainWindow", "Zoom Out (Ctrl + -)"))

