# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graphics_app.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.spinLabel = QtWidgets.QLabel(self.centralwidget)
        self.spinLabel.setText("")
        self.spinLabel.setObjectName("spinLabel")
        self.horizontalLayout_3.addWidget(self.spinLabel)
        self.fileLabel = QtWidgets.QLabel(self.centralwidget)
        self.fileLabel.setText("")
        self.fileLabel.setObjectName("fileLabel")
        self.horizontalLayout_3.addWidget(self.fileLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.aboutButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.aboutButton.setFont(font)
        self.aboutButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Assets/icons8-info-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutButton.setIcon(icon)
        self.aboutButton.setIconSize(QtCore.QSize(30, 30))
        self.aboutButton.setObjectName("aboutButton")
        self.verticalLayout_2.addWidget(self.aboutButton)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.buttonZoomIn = QtWidgets.QToolButton(self.centralwidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Assets/icons8-zoom-in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonZoomIn.setIcon(icon1)
        self.buttonZoomIn.setIconSize(QtCore.QSize(60, 60))
        self.buttonZoomIn.setObjectName("buttonZoomIn")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.buttonZoomIn)
        self.buttonZoomOut = QtWidgets.QToolButton(self.centralwidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Assets/icons8-zoom-out.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonZoomOut.setIcon(icon2)
        self.buttonZoomOut.setIconSize(QtCore.QSize(60, 60))
        self.buttonZoomOut.setObjectName("buttonZoomOut")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.buttonZoomOut)
        self.buttonRotateCCW = QtWidgets.QToolButton(self.centralwidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Assets/icons8-rotate-left-filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRotateCCW.setIcon(icon3)
        self.buttonRotateCCW.setIconSize(QtCore.QSize(60, 60))
        self.buttonRotateCCW.setObjectName("buttonRotateCCW")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.buttonRotateCCW)
        self.buttonRotateCW = QtWidgets.QToolButton(self.centralwidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Assets/icons8-rotate-right-filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRotateCW.setIcon(icon4)
        self.buttonRotateCW.setIconSize(QtCore.QSize(60, 60))
        self.buttonRotateCW.setObjectName("buttonRotateCW")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.buttonRotateCW)
        self.buttonFlipV = QtWidgets.QToolButton(self.centralwidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Assets/icons8-flip-vertical-filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonFlipV.setIcon(icon5)
        self.buttonFlipV.setIconSize(QtCore.QSize(60, 60))
        self.buttonFlipV.setObjectName("buttonFlipV")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.buttonFlipV)
        self.buttonFlipH = QtWidgets.QToolButton(self.centralwidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Assets/icons8-flip-horizontal-filled.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonFlipH.setIcon(icon6)
        self.buttonFlipH.setIconSize(QtCore.QSize(60, 60))
        self.buttonFlipH.setObjectName("buttonFlipH")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.buttonFlipH)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.openButton.setFont(font)
        self.openButton.setObjectName("openButton")
        self.verticalLayout_2.addWidget(self.openButton)
        self.loadLatestButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadLatestButton.sizePolicy().hasHeightForWidth())
        self.loadLatestButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.loadLatestButton.setFont(font)
        self.loadLatestButton.setIconSize(QtCore.QSize(60, 60))
        self.loadLatestButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.loadLatestButton.setObjectName("loadLatestButton")
        self.verticalLayout_2.addWidget(self.loadLatestButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 5, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.defaultDrive = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultDrive.sizePolicy().hasHeightForWidth())
        self.defaultDrive.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.defaultDrive.setFont(font)
        self.defaultDrive.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToMinimumContentsLength)
        self.defaultDrive.setMinimumContentsLength(1)
        self.defaultDrive.setObjectName("defaultDrive")
        self.horizontalLayout_2.addWidget(self.defaultDrive)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(-1, 6, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scaleUpButton = QtWidgets.QToolButton(self.centralwidget)
        self.scaleUpButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Assets/icons8-plus-math-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scaleUpButton.setIcon(icon7)
        self.scaleUpButton.setIconSize(QtCore.QSize(30, 30))
        self.scaleUpButton.setObjectName("scaleUpButton")
        self.gridLayout_2.addWidget(self.scaleUpButton, 1, 2, 1, 1)
        self.scaleDownButton = QtWidgets.QToolButton(self.centralwidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Assets/icons8-subtract-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.scaleDownButton.setIcon(icon8)
        self.scaleDownButton.setIconSize(QtCore.QSize(30, 30))
        self.scaleDownButton.setObjectName("scaleDownButton")
        self.gridLayout_2.addWidget(self.scaleDownButton, 1, 0, 1, 1)
        self.scaleLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.scaleLabel.setFont(font)
        self.scaleLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scaleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scaleLabel.setObjectName("scaleLabel")
        self.gridLayout_2.addWidget(self.scaleLabel, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setFormat("")
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.cancelButton = QtWidgets.QToolButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.cancelButton.setFont(font)
        self.cancelButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Assets/icons8-cancel-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancelButton.setIcon(icon9)
        self.cancelButton.setIconSize(QtCore.QSize(30, 30))
        self.cancelButton.setCheckable(False)
        self.cancelButton.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.cancelButton.setObjectName("cancelButton")
        self.verticalLayout_2.addWidget(self.cancelButton)
        self.fileInfoWidget = QtWidgets.QWidget(self.centralwidget)
        self.fileInfoWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.fileInfoWidget.setObjectName("fileInfoWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.fileInfoWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fileInfoLayout = QtWidgets.QGridLayout()
        self.fileInfoLayout.setContentsMargins(-1, -1, -1, 0)
        self.fileInfoLayout.setObjectName("fileInfoLayout")
        self.sizeLabel = QtWidgets.QLabel(self.fileInfoWidget)
        self.sizeLabel.setText("")
        self.sizeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sizeLabel.setObjectName("sizeLabel")
        self.fileInfoLayout.addWidget(self.sizeLabel, 9, 2, 1, 1)
        self.speedTextLabel = QtWidgets.QLabel(self.fileInfoWidget)
        self.speedTextLabel.setObjectName("speedTextLabel")
        self.fileInfoLayout.addWidget(self.speedTextLabel, 16, 0, 1, 1)
        self.linesLabel = QtWidgets.QLabel(self.fileInfoWidget)
        self.linesLabel.setText("")
        self.linesLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.linesLabel.setObjectName("linesLabel")
        self.fileInfoLayout.addWidget(self.linesLabel, 15, 2, 1, 1)
        self.speedLabel = QtWidgets.QLabel(self.fileInfoWidget)
        self.speedLabel.setText("")
        self.speedLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speedLabel.setObjectName("speedLabel")
        self.fileInfoLayout.addWidget(self.speedLabel, 16, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.fileInfoWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.fileInfoLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.fileInfoWidget)
        self.label_7.setObjectName("label_7")
        self.fileInfoLayout.addWidget(self.label_7, 15, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.fileInfoWidget)
        self.label_3.setObjectName("label_3")
        self.fileInfoLayout.addWidget(self.label_3, 14, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.fileInfoWidget)
        self.label_8.setObjectName("label_8")
        self.fileInfoLayout.addWidget(self.label_8, 13, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.fileInfoWidget)
        self.label_6.setObjectName("label_6")
        self.fileInfoLayout.addWidget(self.label_6, 9, 0, 1, 1)
        self.timeLabel = QtWidgets.QLabel(self.fileInfoWidget)
        self.timeLabel.setText("")
        self.timeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.fileInfoLayout.addWidget(self.timeLabel, 13, 2, 1, 1)
        self.dateLabel = QtWidgets.QLabel(self.fileInfoWidget)
        self.dateLabel.setText("")
        self.dateLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dateLabel.setObjectName("dateLabel")
        self.fileInfoLayout.addWidget(self.dateLabel, 14, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.fileInfoLayout)
        self.verticalLayout_2.addWidget(self.fileInfoWidget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRotate = QtWidgets.QAction(MainWindow)
        self.actionRotate.setObjectName("actionRotate")
        self.actionFlipV = QtWidgets.QAction(MainWindow)
        self.actionFlipV.setObjectName("actionFlipV")
        self.actionZoom_Out = QtWidgets.QAction(MainWindow)
        self.actionZoom_Out.setObjectName("actionZoom_Out")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionRotate_CCW_Ctrl = QtWidgets.QAction(MainWindow)
        self.actionRotate_CCW_Ctrl.setObjectName("actionRotate_CCW_Ctrl")
        self.actionOpen_Latest_Ctrl_L = QtWidgets.QAction(MainWindow)
        self.actionOpen_Latest_Ctrl_L.setObjectName("actionOpen_Latest_Ctrl_L")
        self.actionKeybindings = QtWidgets.QAction(MainWindow)
        self.actionKeybindings.setObjectName("actionKeybindings")
        self.actionViewing = QtWidgets.QAction(MainWindow)
        self.actionViewing.setObjectName("actionViewing")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quicklooks Viewer"))
        self.buttonZoomIn.setText(_translate("MainWindow", "+"))
        self.buttonZoomOut.setText(_translate("MainWindow", "-"))
        self.buttonRotateCCW.setText(_translate("MainWindow", "CCW"))
        self.buttonRotateCW.setText(_translate("MainWindow", "CW"))
        self.buttonFlipV.setText(_translate("MainWindow", "FV"))
        self.buttonFlipH.setText(_translate("MainWindow", "FH"))
        self.openButton.setText(_translate("MainWindow", "Open..."))
        self.loadLatestButton.setText(_translate("MainWindow", "View Latest"))
        self.label_4.setText(_translate("MainWindow", "Drive:"))
        self.label.setText(_translate("MainWindow", "Resolution"))
        self.scaleDownButton.setText(_translate("MainWindow", "-"))
        self.scaleLabel.setText(_translate("MainWindow", "100%"))
        self.speedTextLabel.setText(_translate("MainWindow", "Load Speed:"))
        self.label_2.setText(_translate("MainWindow", "File Info"))
        self.label_7.setText(_translate("MainWindow", "Lines:"))
        self.label_3.setText(_translate("MainWindow", "Date:"))
        self.label_8.setText(_translate("MainWindow", "Time:"))
        self.label_6.setText(_translate("MainWindow", "Size:"))
        self.actionOpen.setText(_translate("MainWindow", "Open (Ctrl + O)"))
        self.actionRotate.setText(_translate("MainWindow", "Rotate CW (Ctrl + >)"))
        self.actionFlipV.setText(_translate("MainWindow", "Flip Vertical (Ctrl + V)"))
        self.actionZoom_Out.setText(_translate("MainWindow", "Flip Horizontal (Ctrl + H)"))
        self.actionZoomIn.setText(_translate("MainWindow", "Zoom In (Ctrl + +)"))
        self.actionZoomOut.setText(_translate("MainWindow", "Zoom Out (Ctrl + -)"))
        self.actionRotate_CCW_Ctrl.setText(_translate("MainWindow", "Rotate CCW (Ctrl + <)"))
        self.actionOpen_Latest_Ctrl_L.setText(_translate("MainWindow", "Open Latest (Ctrl + L)"))
        self.actionKeybindings.setText(_translate("MainWindow", "Keyboard Shortcuts"))
        self.actionViewing.setText(_translate("MainWindow", "Viewing a File"))

